swagger: '2.0'
info:
  version: '0'
  title: 'API 文档'
  description: 'Hello World!'
_json: &json
  code:
    type: 'integer'
    description: '状态码，1 为成功，其它为失败。'
  message:
    type: 'string'
    description: '消息内容，可以直接显示给用户。'
basePath: '/api'
paths:
  api/login:
    post:
      summary: '登录'
      description: '登录'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
        - in: 'body'
          required: true
          schema:
            type: 'object'
            properties:
              username:
                type: 'string'
                description: '用户名'
              password:
                type: 'string'
                description: '密码'
      responses:
        200:
          description: '登录'
          schema:
            type: 'object'
            properties:
              result:
                type: 'string'
                description: '请求结果'
              data:
                type: 'array'
                items:
                  $ref: '#/definitions/User'
              token:
                type: 'string'
                description: 'token'
definitions:
  User:
    type: 'object'
    properties:
      uid:
        type: 'string'
        description: '用户 uid'
      username:
        type: 'string'
        description: '用户名'
      password:
        type: 'string'
        description: '密码'
      role:
        type: 'string'
        description: '权限'
      trueName:
        type: 'string'
        description: '真实姓名'
      tel:
        type: 'string'
        description: '电话号码'
      regTime:
        type: 'string'
        description: '注册时间'